title: My portfolio
description: A portfolio

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: jameson-pi
blog_url: https://www.nagekar.com
email: piscitello284@gmail.com

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
